### ISSUE TITLE
Deprecation Warning!

### ISSUE THREAD

**Issue by Adarrical** [samamorgan/discourse#10]
Hi Sam, 
I use your code and it runs fine until today. 
I get SSL:CERTIFICATE_VERIFY_FAILED error and bad news in discourse page: 

https://meta.discourse.org/t/discourse-api-documentation/22706

Any idea? 

Thanks in advace. 
Albert Darrical.

**Comment by samamorgan** [comment]
All tests are passing for me. This module does use HTTP header auth by default. Can you share some simple code that reproduces the bug?

**Comment by Adarrical** [comment]
Hi Sam, 
The last week it runs fine! I don't understand. 
This is my method code: 

```python
def search_posts(term):
    client = discourse.Client(
         host='https://foro.ojodigital.com/',
         api_username='Albert',
         api_key='this put my api key',
    )
        
    response = client.search(term)
    return response
```

and call method.... 

```python
fecha_inicio = con_input.gettime()   
fecha_fin = (fecha_inicio + timedelta(days=6))  

query = f'{fecha_inicio.strftime("%d")}-{fecha_inicio.strftime("%m")}-{fecha_inicio.strftime("%Y")} al {fecha_fin.strftime("%d")}-{fecha_fin.strftime("%m")}-{fecha_fin.strftime("%Y")} in:title'

response = search_posts(query)
```

The error: 
```lang-none
Exception has occurred: SSLError
HTTPSConnectionPool(host='foro.ojodigital.com', port=443): Max retries exceeded with url: /search.json?q=03-05-2021+al+09-05-2021+in%3Atitle&include_blurbs=True (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)')))
```


Thaks a lot!

**Comment by samamorgan** [comment]
I suspect there's some sort of problem with SSL on that server. Have you tried changing the host from HTTPS to HTTP?

Off-topic, here's an easier way to format those datetime strings

```python
query = f'{fecha_inicio:%d-%m-%Y} al {fecha_fin:%d-%m-%Y} in:title'
```

**Comment by samamorgan** [comment]
I'm able to reproduce the error with this server, both in HTTPS and HTTP modes. It's very likely this is an issue with the server and not this codebase.

I am able to bypass the error by adding `verify=False` to the request as outlined in the documentation:

https://2.python-requests.org/en/master/user/advanced/#ssl-cert-verification

That isn't a change I'll add to this module, so if you want to remove SSL verification, you'll have to subclass or monkey patch this module in your code. I don't recommend that though, it's better to fix the issue with the server's SSL certificate.

**Comment by Adarrical** [comment]
Thanks a lot Sam, 
Sorry for not answering earlier . 
With verification=False program runs fine. 
Server administrator tells me that everything is correct .... 

thanks for date off-topic.!!!!

**Comment by ariznaf** [comment]
HTTP does not work in the server because it only accepts secure access using https.
All http access is redirected to https.

Access using https in any web client is correct and the certificate is valid and verified in firefox, chrome, microsoft edge...

All of them tell you that the certificate is valid and the site is secured.

The error does not give any clue about what the problem may be.

How does the program verify the certificate?
May be that the intermediate certificates authority are not updated in the client or something like that?

Does python verify certificates in a way different than the main web navigators? (I do not program in python).

I have no clue about what the problem may be, as the problem is only with this python script and the error is not too verbose.

I suspect that the CA authority is not recognized byt the python script. We had previously problems with that in a computer that had not the root CA up to date.

The chain of certificates is

DigiCert Global Root CA
---- Encryption Everywhere DV TLS CA - G1
----------- *.foro.ojodigital.com

Previous SSL certificate had a different chain (our domain provider has changed the certificate provider).

Any way we can test if the CA chain is recognized by python?
Is there a way to update CAs used by python?

Thank you a lot.

**Comment by samamorgan** [comment]
I'm afraid this isn't my area of expertise, so I can't really help with issues like this. This module is an abstraction of [`requests`](https://github.com/psf/requests), which has nearly become the de-facto Python HTTP library. I'd suggest opening up an issue there.
