### ISSUE TITLE
Access to category class 

### ISSUE THREAD

**Issue by Adarrical** [samamorgan/discourse#7]
Hi Sam,

   We want use package discourse but i get an error. I'm very nobel programmer and i don't know where's the problem. Can you help me please.
   I want to access category topic's. 

This is my code:

```python
import discourse
import json

from discourse.category import Category

client = discourse.Client(
        host = 'http://foro.ojodigital.com',
        api_username = 'Albert',
        api_key='my api keyf')

categorylist = '{"category":13}'
jsoncat = json.loads(categorylist)

categories = Category(client,jsoncat)
```

The error is:
```python
Traceback (most recent call last):
  File "C:\Pruebaspy\test_url.py", line 14, in <module>

    categories = Category(client,jsoncat)
TypeError: __init__() takes 2 positional arguments but 3 were given

[Finished in 0.349s]
```

Thanks in advance.
Albert

**Comment by samamorgan** [comment]
This is happening because categories aren't meant to be handled directly, these objects are created when you call a get function from [`Client`](https://github.com/samamorgan/discourse/blob/master/discourse/client.py), then you can call the sub-functions in the returned object to perform further actions on that object.

There's no single-category endpoint in the [Discourse API](https://docs.discourse.org/#tag/Categories), so you have to [get a list of all categories](https://docs.discourse.org/#tag/Categories/paths/~1categories.json/get) then parse out the one you want. Here's the correct way to retrieve all categories:

```python
import discourse

client = discourse.Client(
    host = 'http://foro.ojodigital.com',
    api_username = 'Albert',
    api_key='my api keyf',
)

categories = client.get_category_list()
```

If you want a specific category from there, you have to parse over the list and retrieve based on object properties. There are several ways to do this:

```python
# One-liner way, either retrieves category #13 or None
category = next((c for c in categories if c.id == 13), None)

print(category)
```

```python
# Loop-break version, much clearer if you're new to python
category = None
for c in categories:
    if c.id == 13:
        category = c

print(category)
```

**Comment by samamorgan** [comment]
I'd like to note that I've only implemented the documented endpoints. There very well may be an endpoint for a single category, but the Discourse API is not fully documented.

If you find an undocumented endpoint, please do open an issue here and I'll add it to this library!
